version: '3.4'

#========
# Common variables
#========
x-common-variables: &common-variables
  DATASOURCE_HOST: ${DB_HOST}
  DATASOURCE_USER: ${DB_USER}
  DATASOURCE_PASSWORD: ${DB_PASSWORD}
  DATASOURCE_NAME: ${DB_DATABASE}
  DATASOURCE_PORT: ${DB_PORT}


services:
  mysqldb:
    image: mysql

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mystorage:/var/lib/mysql

  ecomm-products:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6666:6666"
    depends_on:
      - mysqldb
    restart: always
    environment:
      <<: *common-variables

volumes:
  mystorage: